#ifndef DFPROTO_INCLUDED
#include "world_landmass.h"
#endif
METHOD_GET_LIST(WorldLandmass, world_landmass, landmasses)

#ifndef DFPROTO_INCLUDED
#include "world_mountain_peak.h"
#endif
METHOD_GET_LIST(WorldMountainPeak, world_mountain_peak, mountain_peaks)

#ifndef DFPROTO_INCLUDED
#include "world_region.h"
#endif
METHOD_GET_LIST(WorldRegion, world_region, regions)

#ifndef DFPROTO_INCLUDED
#include "world_river.h"
#endif
METHOD_GET_LIST(WorldRiver, world_river, rivers)

#ifndef DFPROTO_INCLUDED
#include "world_underground_region.h"
#endif
METHOD_GET_LIST(WorldUndergroundRegion, world_underground_region, underground_regions)
